### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by nek7u** [beckorz/atto#1]
はじめまして。
本日(2021-03-24)こちらのリポジトリに出会いまして、面白いコンセプト/便利なソフトと感じました。
自分は普段 [Rainmeter](https://www.rainmeter.net/) というソフト向けのスキン(ガジェット)を作っていまして [FeedMoe](https://github.com/nek7u/FeedMoe)、是非 Rainmeter版の atto を作って公開したいと思い立ち、許可/了承を頂きたくコメントします。

#### 内容
- [X] 将来的にも非商用/無料で公開すること
- [X] スキンの公開先は [nek7u/ScreenshotMoe](https://github.com/nek7u/ScreenshotMoe) と [Rainmeterのフォーラム](https://forum.rainmeter.net/viewforum.php?f=27)
- [X] スキンの名前は ScreenshotMoe (仮)
- [X] Creditに beckorz さんの名前と リポジトリへのリンク [beckorz/atto](https://github.com/beckorz/atto) を載せる

<details><summary>試作のプレビュー</summary>

![](https://raw.githubusercontent.com/nek7u/Notes-for-Rainmeter-Skins/main/m/SSMoeDraftPreview.gif)

</details>

**Comment by beckorz** [comment]
はじめまして。

ご連絡ありがとうございます。
既にそこまで作っているとは、すごいですね。
許可いたしますので、よろしくお願いいたします👍
逆に私も大変興味がありますので、是非使わせていただければと思います。

**Comment by nek7u** [comment]
素早い返事ありがとうございます。
では これから試行錯誤しながら制作してみます。
公開した時に またコメントします。

<details><summary>2021-03-27 preview</summary>

![](https://raw.githubusercontent.com/nek7u/Notes-for-Rainmeter-Skins/main/m/SSMoeDraftPreview2.gif)

</details>

<details><summary>2021-03-30 preview</summary>

![](https://raw.githubusercontent.com/nek7u/Notes-for-Rainmeter-Skins/main/m/SSMoeDraftPreview3.gif)

</details>

<details><summary>2021-04-02 preview</summary>

![](https://raw.githubusercontent.com/nek7u/Notes-for-Rainmeter-Skins/main/m/SSMoeDraftPreview4.gif)

</details>

**Comment by nek7u** [comment]
こんにちは。
Rainmeterスキン [Snip and Pin to Screen](https://github.com/nek7u/Snip-and-Pin-to-Screen/wiki), inspired by [atto](https://github.com/beckorz/atto) を公開しましたので、連絡いたします。
1. https://github.com/nek7u/Snip-and-Pin-to-Screen/wiki
2. https://forum.rainmeter.net/viewtopic.php?t=41475

デフォルトのスキン インストール場所 `C:\Users\%UserName%\Documents\Rainmeter\Skins\Snip and Pin to Screen`  
デフォルトのスクリーンショット保存場所 `C:\Users\%UserName%\Pictures\Snip and Pin to Screen`   

スキンを右クリックすればコンテキスト メニューから色々と設定を変更できます。
Windows Nativeのコンテキスト メニューと違って、サブ メニューを開くにはさらに**左クリック**する必要があります。
画像ビューアーは１つで、マウススクロールで画像を変更するタイプになっています。

**Comment by beckorz** [comment]
返信が遅れ、すみません。

良いですね。使ってみました。
attoよりすごい使いやすい機能が実装されており、私の方も参考にさせていただきます。
最近attoの開発が滞っておりますが、いい刺激になりました。
今後ともそちらも頑張ってください。

**Comment by nek7u** [comment]
Close #1
